version: 2.1
jobs:
  build:
    docker:
      - image: haskell:8.4.4
    steps:
      - checkout
      - run:
          name: Download and add nodejs apt
          command: "curl -sL https://deb.nodesource.com/setup_12.x | bash -"
      - run:
          name: Install apt packages
          command: "apt update && apt install -y curl nodejs"
      - run:
          name: Install netlify-cli
          command: npm install netlify-cli -g
      - run:
          name: Link netlify site
          command: "netlify link --name gphil"
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - dependencies-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run: stack build
      - save_cache:
          name: Cache Dependencies
          key: dependencies-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run: stack exec site build
      - run:
          name: Deploy
          command: netlify deploy --dir _site/ --prod
workflows:
  build:
    jobs:
      - build
  context: gphil.net